repos:
  - repo: https://github.com/standard/standard
    rev: v17.0.0
    files: "./src/**/*.js"
    hooks:
      - id: standard

  - repo: https://github.com/thibaudcolas/pre-commit-stylelint
    rev: v14.8.5
    files: "./src/**/*.{css|scss}"
    hooks:
      - id: stylelint
        additional_dependencies:
          - stylelint@14.8.5
          - stylelint-config-html@1.0.0
          - stylelint-config-prettier@9.0.3
          - stylelint-config-prettier-scss@0.0.1
          - stylelint-config-standard@25.0.0
          - stylelint-config-standard-scss@4.0.0
