-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Command exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


erase : Translations -> String
erase translations =
    t translations "command.erase"


reset : Translations -> String
reset translations =
    t translations "command.reset"


speak : Translations -> String
speak translations =
    t translations "command.speak"


spell : Translations -> String
spell translations =
    t translations "command.spell"


submit : Translations -> String
submit translations =
    t translations "command.submit"


retry : Translations -> String
retry translations =
    t translations "command.retry"


new : Translations -> String
new translations =
    t translations "command.new"


soundOn : Translations -> String
soundOn translations =
    t translations "command.soundOn"


soundOff : Translations -> String
soundOff translations =
    t translations "command.soundOff"
