-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Init exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


message : Translations -> String
message translations =
    t translations "init.message"
