-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations.Screen exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


word : Translations -> String
word translations =
    t translations "screen.word"


definition : Translations -> String
definition translations =
    t translations "screen.definition"


pronunciation : Translations -> String
pronunciation translations =
    t translations "screen.pronunciation"
